=== dmytromk/s5_labs/OOP/lab2/lab2/src/main/resources/internet-page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="sites">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="site" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="type" type="siteType"/>
                        <xs:element name="has_authorization" type="xs:boolean"/>
                        <xs:element name="characteristics" type="characteristics" minOccurs="0"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="siteType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Advertisement"/>
            <xs:enumeration value="News"/>
            <xs:enumeration value="Portal"/>
            <xs:enumeration value="Mirror"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="characteristics">
        <xs:sequence>
            <xs:element name="has_email" type="xs:boolean"/>
            <xs:element name="has_news" type="xs:boolean"/>
            <xs:element name="has_archive" type="xs:boolean"/>
            <xs:element name="voting">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="No"/>
                        <xs:enumeration value="Anonymous"/>
                        <xs:enumeration value="Authorized"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="free" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== dmytromk/s5_labs/OOP/lab2/lab2/src/main/resources/internet-page.xml
<?xml version="1.0" encoding="UTF-8" ?>

<sites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="internet-page.xsd">
    
    <site id="site1">
        <title>CNN</title>
        <type>News</type>
        <has_authorization>false</has_authorization>
        <characteristics>
            <has_email>true</has_email>
            <has_news>true</has_news>
            <has_archive>false</has_archive>
            <voting>Anonymous</voting>
            <free>true</free>
        </characteristics>
    </site>

    <site id="site2">
        <title>Advertisement Pro</title>
        <type>Advertisement</type>
        <has_authorization>false</has_authorization>
    </site>

    <site id="site3">
        <title>Example Portal Site</title>
        <type>Portal</type>
        <has_authorization>true</has_authorization>
        <characteristics>
            <has_email>true</has_email>
            <has_news>false</has_news>
            <has_archive>true</has_archive>
            <voting>Authorized</voting>
            <free>true</free>
        </characteristics>
    </site>

</sites>
