=== dmytromk/s5_labs/Distributed Calculations/lab7/src/main/resources/airline.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="airline" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="flights" type="flights" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="country" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="flights">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="xs:string" use="required"/>
        <xs:attribute name="destination" type="xs:string" use="required"/>
        <xs:attribute name="price" type="xs:integer" use="required"/>
    </xs:complexType>

</xs:schema>

=== dmytromk/s5_labs/Distributed Calculations/lab7/src/main/resources/airline.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="airline.xsd">

    <airline id="A001" name="Airline1" country="Country1">
        <flights name="Flight1" origin="City1" destination="City2" price="500"/>
        <flights name="Flight2" origin="City3" destination="City4" price="700"/>
    </airline>

    <airline id="A002" name="Airline2" country="Country2">
        <flights name="Flight3" origin="City5" destination="City6" price="600"/>
        <flights name="Flight4" origin="City7" destination="City8" price="800"/>
    </airline>

    <airline id="A003" name="Airline3" country="Country3">
        <flights name="Flight5" origin="City9" destination="City10" price="550"/>
    </airline>

</collection>
